# Generated by Django 6.0 on 2026-05-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('error', 'Помилка')], max_length=10)),
                ('error_type', models.CharField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог завантаження',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=500)),
                ('impr', models.BigIntegerField(default=0)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to=settings.AUTH_USER_MODEL)),
                ('upload_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='uploads.fileuploadlog')),
            ],
            options={
                'verbose_name': 'Запис даних',
                'ordering': ['-year', 'advertiser'],
            },
        ),
    ]
